name: Unrivaled
options:
  bundleIdPrefix: com.unrivaled
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    DEVELOPMENT_TEAM: ""

targets:
  Unrivaled:
    type: application
    platform: iOS
    sources:
      - path: UnrivaledApp/Sources
    settings:
      base:
        INFOPLIST_FILE: UnrivaledApp/Resources/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unrivaled.app
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    dependencies:
      - target: UnrivaledWidget
        embed: true
    entitlements:
      path: UnrivaledApp/Resources/Unrivaled.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.unrivaled.app
  
  UnrivaledWidget:
    type: app-extension
    platform: iOS
    sources:
      - path: UnrivaledWidget
    settings:
      base:
        INFOPLIST_FILE: UnrivaledWidget/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.unrivaled.app.widget
        ASSETCATALOG_COMPILER_WIDGET_BACKGROUND_COLOR_NAME: WidgetBackground
    entitlements:
      path: UnrivaledWidget/UnrivaledWidget.entitlements
      properties:
        com.apple.security.application-groups:
          - group.com.unrivaled.app
